### ISSUE TITLE
PROCESS CHANGE: Adopt CNCF Slack

### ISSUE THREAD

**Issue by lance** [knative/community#1043]
With Knative's move to CNCF as the governing body, we need to determine how to move forward with Slack. Currently the Knative Slack is paid for by Google and the monthly cost is quite high. CNCF will not shoulder this burden and Knative will eventually not have the financial support from Google to do so. We have a few options.

- Move to another platform altogether - for example Discord
- Move to the CNCF Slack
- Find funding for the existing Knative Slack

It is unlikely that we will find additional funding, so in truth our only two options are to adopt another platform or move to CNCF Slack. Over the last couple of months this has been discussed in the Steering Committee, and it's mostly agreed that moving to CNCF Slack is the correct path forward. (If you disagree, please feel free to comment in this issue)

In adopting the CNCF Slack, we will need to map the existing Knative Slack channels to new channels that designate them as Knative. For example the `#general` channel will become `#knative`, and the `#eventing` channel will become `#knative-eventing`. Even so, there are a lot (59) Knative channels. It would be wise to reduce this number and archive channels that are no longer relevant. This archival also introduces the question of where we should archive past channels that are not moving over.

**Comment by dprotaso** [comment]
It would be great if there was a way to export all the public history to some online format that we could search. For example there have been a steady set of questions in #serving-questions - having access to that history would be useful to users and future contributors.

**Comment by evankanderson** [comment]
If we can extract the data from Slack, it seems like we might be able to store the archives either in GSuite or in object-store buckets. Since we would only be archiving public channels, it seems reasonable to be able to publish these elsewhere.

https://slack.com/help/articles/201658943-Export-your-workspace-data#:~:text=Select%20Settings%20%26%20administration%20from%20the%20menu%2C%20then%20click%20Organization%20settings,and%20select%20a%20date%20range.

suggests that we should be able to export messages from public channels using the tool to get a zip file.

**Comment by csantanapr** [comment]
From the last discussion in Steering, @thisisnotapril was going to look at Slack usage and propose the set of channels to be created in CNCF.

**Comment by dprotaso** [comment]
This is done - but anyone know where the old slack archive is located? I thought it would be in the Knative Team Drive

**Comment by aliok** [comment]
/close

Closing this, but feel free to reopen if you think we need the archive
