### ISSUE TITLE
Enable Codespaces for Knative?

### ISSUE THREAD

**Issue by psschwei** [knative/community#1295]
Via the CNCF, there's an offer from Github to help set up and enable Codespaces for Knative, so creating an issue for us to discuss. Not sure if this falls under TOC or Steering, but for now will add it to the TOC board...

**Comment by psschwei** [comment]
cc @knative/technical-oversight-committee @knative/steering-committee

**Comment by evankanderson** [comment]
Dave would better like to understand what this means, since you can use Codespaces on the fork.

**Comment by evankanderson** [comment]
@dprotaso @kvmware @upodroid have been meeting with a GitHub TPM, will follow up on this.

**Comment by dprotaso** [comment]
Contact has been made here - https://github.com/knative/community/issues/1295

**Comment by dprotaso** [comment]
Following up - the experience of using Codespaces in Serving is poor when using the default prow image that has all the tools installed. Start times are slow. A way to mitigate that is to use prebuilt codespaces - but this can't be leveraged by non-Knative members since this requires opening the codespace in the knative org which is a non-starter.

Based on this I don't recommend a project wide initiative to continue this further. Though I won't object if subgroups choose to try it themselves.

I'll leave the Serving issue open in case someone volunteers to try to improve what's been there but overall. 


I'm going to close this out.

**Comment by craiglpeters** [comment]
I think that prebuilding a container with the prow image as your base image will do the trick. https://containers.dev/guide/prebuild Reach out in Kubernetes Slack to craiglpeters if I can be of help

**Comment by Cali0707** [comment]
Cc @r2-lf
