### ISSUE TITLE
Clarify scope of Knative

### ISSUE THREAD

**Issue by isdal** [knative/community#131]
The steering committee should publish clear guidelines for which efforts are considered within scope for Knative and the Knative org.

**Comment by isdal** [comment]
We had spent some with between the SC and the TOC to clarify what we consider in scope for Knative. The draft is here and open for feedback.

https://docs.google.com/document/d/1Jj9Kw5wmsqbal0GHabl0OG9xnOzKqbCxdkYak9QzlSk/edit

**Comment by pmorie** [comment]
I think that our recent discussions on governance have added a lot of clarity on this matter. At the moment, I feel like we have wide consensus throughout the project that the _current_ scope is: serving, eventing, and CLI. Encoding this scope officially seems like a reasonable way to start and relatively simple activity for the KTC to execute.

Related to this is that with that scope clarified and established, it seems like we would be in a position to have a good conversation about whether we're ready to call that scope 1.0, since that's an important psychological threshold to meet for adoption.

**Comment by evankanderson** [comment]
That's an interesting question -- do we think that KTC needs to have established branding/licensing standards to have a 1.0 release? That feels like it would be a 1.0 worthy milestone to me.

**Comment by pmorie** [comment]
That's a good point, I certainly think it would be very helpful if 1.0 included such guidelines

**Comment by evankanderson** [comment]
We have established a conformance process (currently waiting on CNCF support ticket / lawyer attention to make it official), and we have https://github.com/knative/community/blob/main/mechanics/MATURITY-LEVELS.md#migration-to-core describing the criteria for `-sandbox` vs "core Knative".

I think we _can_ close this.

/close
