### ISSUE TITLE
Knative 1.10 support till Feb 2023?

### ISSUE THREAD

**Issue by RamanDxc** [knative/community#1440]
Hi,

I am interested in knowing will KNative 1.10 will support Kubernetes version 1.25.7 till Feb 2023?
Please provide the detailed answer. If Yes - I am good.
If No, What version we should be on minimum for 1.25.7 K8s till Feb 2023?
Also Since Istio work hand-on-hand with Knative, If you can answer Istio 1.17 will work with (K8s 1.25.7 and Knative 1.10) till Feb 2023?

Thanks,
Raman

**Comment by dsimansk** [comment]
Hi @RamanDxc, by any chance did you mean Feb 2024 rather than 2023?

I'll assume 2024 is your target year. In the community we are supporting 2 released version in parallel.[1] Knative 1.10 will go out of support at the end of October 2023. It's just behind the corner.
Also please check our versioning principles for more details.[2] We are testing several Kubernetes versions ranging from minimal required to latest in the CI periodically. Therefore I believe unless Kubernetes or Istio would ship a surprising breaking change in their patch releases it should work as expected.

Knative Serving 1.10 was tested & shipped with Istio 1.17 version. Yes, it should work in that combination.

Depending how critical your production environment is. Then Knative 1.11 will be EOL at the and of January 2024. I'd not expect that release breaking in a month between.  

[1] https://github.com/knative/community/blob/main/mechanics/RELEASE-SCHEDULE.md#releases-supported-by-community 
[2] https://github.com/knative/community/blob/main/mechanics/RELEASE-VERSIONING-PRINCIPLES.md

**Comment by dsimansk** [comment]
@knative/serving-wg-leads FYI and possible further details.

**Comment by dprotaso** [comment]
net-istio v1.10 has been tested with istio v1.17 - we mention it on our release notes here
https://github.com/knative-extensions/net-istio/releases/tag/knative-v1.10.0

**Comment by RamanDxc** [comment]
Thanks for sharing the details. I still would like to get the information
in simple words. :)

KNative 1.10 will be supported till Feb 2024? Yes/No
Istio 1.17 will be supported till Feb 2024? Yes/No
These both combinations can be used till Feb 2024 with support? Yes/No
If answer is NO for any of the above Question, then what's the minimum
version supported during Feb 2024 for both KNative and Istio?

Reason I am asking, we are on this version and don't want to touch it till
Feb 2024, but we also want to make sure these are supported till Feb 2024.
Please confirm !!

Thanks,
Ramandeep
+1-623 383 5112

**Comment by dsimansk** [comment]
>KNative 1.10 will be supported till Feb 2024? Yes/No
 
No, not by the Knative community. It doesn't mean it won't work. 


> Istio 1.17 will be supported till Feb 2024? Yes/No

I can't answer for Istio project. That depends on their support policy.

These both combinations can be used till Feb 2024 with support? Yes/No

**Comment by ReToCode** [comment]
@RamanDxc does [this](https://github.com/knative/community/issues/1440#issuecomment-1731403612) answer your question? If not please feel free to re-open the issue again.
