### ISSUE TITLE
I can not put  community issues into the Knative project board.

### ISSUE THREAD

**Issue by n3wscott** [knative/community#260]
trying to follow the steps for new project. Can't add the issue to the project board if the issue is in  community.

**Comment by grantr** [comment]
@n3wscott and I investigated this. Actually every org member can edit the project (including deleting columns, yikes), **but only from the project page**. The Projects gear on the issue page only appears if the user has permission to edit repository projects, which require repo write access.

This is likely a relic from back before org projects existed. If a user didn't have permission to edit repo-level projects, the gear would never apply to them. But now the gear can apply because the user could add the issue to a project outside the repo.

This should probably be reflected in the template instructions.
