### ISSUE TITLE
User Experience Working Group Proposal 

### ISSUE THREAD

**Issue by omerbensaadon** [knative/community#420]
See: https://docs.google.com/document/d/1K_LGymgqedAzRS0ACdVtJH1ktQxrf1OatfxzIb6LjU0/edit#

**Comment by evankanderson** [comment]
> **Mission**
> The User Experience Working Group is responsible for ensuring that new and existing users easily understand Knative’s core concepts and have a delightful experience using the project.

**Comment by evankanderson** [comment]
Approved at 11 Feb 2021 TOC meeting:

+1: Evan Anderson, Matt Moore, Markus Thömmes, Roland Huß
abstain: Grant Rodgers

**Comment by evankanderson** [comment]
Now we need a PR to add this to community. I'll work with @omerbensaadon / @csantanapr on the PRs.

**Comment by grantr** [comment]
+1 Grant Rodgers

**Comment by julz** [comment]
🎉🎉

**Comment by vaikas** [comment]
Isn't this done already, does this need to be in Steering backlog still?

**Comment by csantanapr** [comment]
@vaikas It looks like the custody of the UX WG will belong to the TOC in the meantime, not the SC.

Since the proposal got accepted by TOC to have custody, I propose we move forward with the tasks to establish the new UX WG.

Once established I'm OK if SC wants to take custody of the UX WG from TOC, we can have a discussion on the next SC meeting just add me and @omerbensaadon

**Comment by csantanapr** [comment]
Setting up the UX WG tasks are being tracked in this issue https://github.com/knative/community/issues/466
