### ISSUE TITLE
PROCESS CHANGE: Add Slack Bot for Slack Threads which exceed 25 messages 

### ISSUE THREAD

**Issue by omerbensaadon** [knative/community#549]
### Expected benefits. Who gains the benefits? Why will they benefit?
If #548 ends up being merged, it would be great to find a way to nudge people in the right direction to discontinue a Slack Thread before it gets unwieldy. 

The bot would say something like "Looks like this thread has hit more than 25 comments, is there a Github issue or Google doc to be written? Should we meet to discuss this?"

### Expected costs. Who bears the costs? How heavy are they?
I will bear the cost of building the Slack bot.

### Timeframe for implementation / rollout.
Shouldn't take more than a day or two? 

### Are you willing to drive the process, or is this a request for help?
Yes

**Comment by markusthoemmes** [comment]
I'm personally okay experimenting with this as long as it doesn't get annoying or too prescribtive. As long as it just acts as a friendly reminder to take stuff of Slack, this might be a step in the right direction.

**Comment by julz** [comment]
Yeah +1 to what @markusthoemmes said. Im ok with a slack bot to nag us to _consider_ if a conversation would be best as an issue, that seems fine and good. OTOH I'd be a bit uncomfortable with anything that feels like we're starting to police the best way for people to communicate iyswim. Assuming this is done in a constructive way (I'm sure it will be but just wanted to call that out!) it seems good.

**Comment by julz** [comment]
Im more concerned that we say something like `"Hi! this is a long thread isnt it! Id like to check that you've considered whether it may be better as an issue or a discussion (Is it something people will want to refer to later? Is it something more people may want to chime in on, etc?) If not, carry on, thanks!"` rather than anything close to `"Hello you've exceeded your thread limit. Please move this to an issue or discussion"` or whatever. Tldr I think there's a lot of slack conversations that are great and useful (while accepting there are many that should have been discussions now discussions exist) and I'm not convinced we need robert overloads policing when that is rather than our own good judgement ;) (but nudges are fine!).

**Comment by julz** [comment]
>  robert overlords

😂 😂 very unintentional typo, which Im going to leave in. Let's call the bot robert.

**Comment by omerbensaadon** [comment]
bahahah I there is something hilarious about `"Hello you've exceeded your thread limit. Please move this to an issue or discussion"`

**Comment by omerbensaadon** [comment]
but yes, that's exactly the sentiment I am going for :)

**Comment by JohnONolan** [comment]
@omerbensaadon Quick question - did you build this slackbot, and is it open source by any chance? I've just been googling for the same thing and found this issue :)

**Comment by psschwei** [comment]
Having been part of some long threads on Slack recently, I haven't been accosted by any robert overlords, so I don't believe this was ever rolled out on Knative slack.

**Comment by arein** [comment]
@JohnONolan how did you end up solving this?
