### ISSUE TITLE
Post-GA Version numbering scheme

### ISSUE THREAD

**Issue by evankanderson** [knative/community#702]
TOC needs to determine a version numbering scheme for post-GA releases.

## Considerations

* How does this play with `go mod` versioning?
* How does this play with the operator and version upgrade safety checks?
* Are the human-factors ergonomics to consider (e.g. "1.26" vs "1.0"? "1.67" as a version number vs "67"? "67" vs "2023-01-14")?

Please add candidate version schemes and pros/cons in this issue.

**Comment by rhuss** [comment]
What's about applying strict [semver 2.0](https://semver.org/) after GA ? I think this semver is well understood, semver version are easily comparable and also quite well accepted by humans. And we kind of have semver already (albeit using the minor version also for breaking changes).

**Comment by evankanderson** [comment]
One concern about semver:

Semver assumes a well-defined public API; assuming that we synchronize version numbers across all components, how do we define our public API?

As a counter-example of semver; Kubernetes 1.22 (and 1.18) removes a number of APIs (alpha and beta); in some cases fields are also deprecated and then disallowed without incrementing the major version (still under the aegis of general backwards compatibility).

It would be nice to be able (for example) to predict Knative version numbers in advance without needing to survey each component. I can see three techniques for doing this:

1. "Rough backwards compatibility" (aka the Kubernetes way). This generally matches the semantics of cloud providers, and suggests that there is a migration path from 1.25 to 1.28, but may require some work on each release.

2. "Conservative strict semver" (aka the Chrome way). Always increment the major version number on coordinated release. Given our current release cadence, minor version numbers would be unlikely. I'm not sure what effect this would have on downstream tools like `dep`.

1. "Breakage windows" (not sure of precedent). Define one or two releases a year which may remove deprecated APIs, etc. Batch all removals into those releases (which might also coincide with quality / cleanup changes), and require other releases to be minor-version changes only.

A lot of this hinges on what we view as our public API:
* All CRD fields?
  * Specific designated CRD fields?
  * annotations and configmap keys?
  * are beta APIs covered?
  * what about packaging (combine / split yaml files)?
* client-go generated bindings?

**Comment by julz** [comment]
I think I would assert that the things people want from semver apply mainly at the CRD level (since that's our api surface), so are more effort/confusion than they're worth for knative itself (triply the case when you consider any subproject may be the thing making a change breaking, unless we're ok with the versions getting out of line, so eventing changing an api could mean serving has to bump major/minor etc - yuck). 

It would seem odd need to eg make knative 2.0 to communicate a breaking change to the Route CRD when we can just make the Route CRD v2 instead and still support v1 of Route. Otherwise would we wait till we remove the v1 Route CRD and _then_ declare knative 2.0, even tho the v2 Route had been available, and the v1 Route deprecated, for months? Seems more confusing than helpful, to me.

I'd lean towards something roughly k8s like: version numbers that just mean "the next version" at the project level, and semver etc happens to CRDs instead. If we worry that creates confusion (tho I think it won't much, since k8s has trained a lot of our users not to expect real semver at the project level), I'd go with dates (2018.3 etc) - but my initial vote is 1.N where N increments forever. It's simple and matches k8s, which is familiar to many of our users. We'd reserve major version number changes for a major event (rewriting the whole thing in rust/wasm/some other buzz-language, most likely).

Separately, we'd need a policy for deprecation and removals of CRD versions, but that could be entirely decoupled from the project/release version issue.

**Comment by lionelvillard** [comment]
FWIW, I'm with Julz. We already have a backward-compatible policy in place (e.g. 0.25 is backward-compatible with 0.24, but not b/c with 0.23), it's all what we need (almost :-) )

**Comment by evankanderson** [comment]
It sounds like a general preference for "1. 'Rough backwards compatibilty'".

My interest in just using major version numbers is that the "1." in front feels redundant.

# Go mod upgrades

For applications using our generated client libraries, using a "1.X" version numbering scheme will tend to upgrade to the latest release automatically. If they have substantially lagged (e.g. "1.7" to "1.15"), the generated client libraries may change, which might cause breakage. Historically, I think one of the large culprits of this has been changes to the k8s code generation libraries.

If we removed the leading "1.", then clients might be likely to "stick" to older versions of the generated client libraries, which might be stable but unaware of newer fields. Each release would broadcast the possibility of breaking API changes, e.g. from "7" -> "15".

Using date-based versions like "2021.7" would appear in Semver to make a "breaking" release once a year; I'm not sure how this would line up with actual breakages in generated code, but it would tend to reduce the amount of "upgrade churn" that clients received _if we could align our breaking changes with year-start releases_.

# Operator and version-based safety checks

Both the "1.X" and the "X" version safety checks could be implemented; the "0.X" -> "1.Y" upgrade will need to be a special case in both cases.

For date-based releases, we'd need to either standardize on the number of releases per year (6*8 = 48, allowing for a few weeks of end-of-year slip), or publish a calendar in some way to handle the "2021.7" -> "2022.0" upgrade.

**Comment by evankanderson** [comment]
Markus suggests that our versioning for `go.mod` could be different than our published version names.

**Comment by evankanderson** [comment]
It came up that we might be able to use two sets of tags; one for the user-visible artifacts, and a separate one for `go.mod`.

General feeling is to roll out with 1.X and add any other tagging scheme later.

Once we have a "GA" release, we'll start over at 1.0.

**Comment by evankanderson** [comment]
Markus pointed out that bumping major versions each time would require more source code changes in downstream consumers:

https://golang.org/ref/mod#major-version-suffixes

> Starting with major version 2, module paths must have a major version suffix like /v2 that matches the major version. For example, if a module has the path example.com/mod at v1.0.0, it must have the path example.com/mod/v2 at version v2.0.0.

**Comment by evankanderson** [comment]
See https://github.com/knative/community/issues/702#issuecomment-902042308 for resolution

/close
