### ISSUE TITLE
PROCESS CHANGE: Introduce end-user seats in steering committee

### ISSUE THREAD

**Issue by bsnchan** [knative/community#731]
## Background
When we transitioned from the bootstrap steering committee to an elected steering committee last year (in 2020), we explored the idea of creating an end-user seat but couldn't quite determine what mechanics we should follow. We [documented](https://github.com/knative/community/blob/main/STEERING-COMMITTEE.md#transition) that we should explore this process again for the 2021 steering elections.

## Proposed Change
* Keep 5 total seats on steering, 4 contributor seats + 1 end-user seat.
* For 2021 steering elections, we have the 3 remaining bootstrap seats up for election. Have 2 of these seats be contributor seats and 1 of these seats be the end-user seat.
* Proposal for election process options:
  * For 2021: Have steering appoint the end-user representative who will stay on the committee for a 1-year term. If the representative leaves their company, stops being an end-user, steps down, steering can reappoint as necessary (thanks @julz for the idea!)
  * For 2022: Create an "end user registry" where users share their user stories. This will give us a pool of "end users" which the community could then vote on (thanks @jberkus for the idea!)

## Benefits
* Lower the bar for end-users to join the community
* Increase representation in the steering committee

## Cost
* We would be losing 1 contributor seat (out of 5 seats)

## Timeframe for implementation/rollout
* We can adopt this process and start evangelizing/sharing before the steering committee elections in late Oct/early Nov
* I don't believe it will require additional work for the election officers

## Are you willing to drive the process, or is this a request for help?
* Yes

**Comment by vaikas** [comment]
If we do not get someone to run, perhaps fall back to contributors?

**Comment by geekygirldawn** [comment]
I'm curious about how we implement this from a voting perspective. Will other end users be able to vote on the end user seat? If so, will end users also be able to vote on the contributor seat? Or do we leave the voting criteria as-is?

@jberkus from an Elekto perspective, would we need to run this as 2 separate elections - one for the end user seat and one for the contributor seats? Or do we run it as one election with people ranking both types of candidates together and select the top 2 contributors and the top end user? This decision impacts @vaikas's PR.

**Comment by vaikas** [comment]
I'm curious about this:

```
The end-user seat would be the "tie-breaker" if there were any decisions that needed tie-breaking
```

why make this distinction specifically? Meaning, if they partake in voting (if a vote is necessary), there's still the majority one way or another. Not trying to disagree, trying to understand why it's special. For example, is it the case they only vote if things come to 2-2, and if so what's the reasoning for that?

What happens if the person works for company XYZ where they use Knative and then they leave to a company where they no longer use it? Or they stop using it for some reason.

**Comment by jberkus** [comment]
Whether or not it's two separate elections depends on who can vote.   Who's voting for the end user seat?

**Comment by julz** [comment]
I like the idea of end-user seats a lot, in general. I tend to agree though, fwiw, that it doesn't make a lot of sense for the voters for those seats to be contributors. Fundamentally I - as a contributor - have no idea which end user would best represent the end-users on steering. 

If the job is to represent end users, it seems that we need the people voting for the seat to be end users, not (as for the other seats), [people who have made at least 50 contributions in the last 12 months](https://github.com/knative/community/blob/main/STEERING-COMMITTEE.md#eligibility-to-vote). 

Unfortunately having a separate pool of voters does seem like it would require a second election (or relaxing the voter requirements across the board). I think on balance it may be worth the second election (and if only 1 person runs it may be an easy election), but it's not my time I'm volunteering, it's the election officer's, obviously, and I do worry about the edge cases (the point about someone no longer working for an end-user company is a very fair one - unlike a contributor seat the end-user seat really is representing users and is not earnt by contributions which follow a person rather than a company, I think). 

An alternative I'll throw in here just for consideration would be to have the steering committee nominate an end user representative each year by consensus or majority, which avoids the extra election and having to worry about the semantics of what happens if someone qualifies by two routes etc, but still gives us an end-user seat.

**Comment by geekygirldawn** [comment]
> An alternative I'll throw in here just for consideration would be to have the steering committee nominate an end user representative each year by consensus or majority, which avoids the extra election and having to worry about the semantics of what happens if someone qualifies by two routes etc, but still gives us an end-user seat.

+1 to this alternative from @julz, and not just because it simplifies my life as an election officer :) Having this be a nominated / appointed seat, gives the Steering Committee more flexibility and avoid some of the complexity / confusion associated with having a second type of election.

**Comment by bsnchan** [comment]
@julz: 

I like that suggestion! Re: the edge case around an individual leaving a company, perhaps we can spell it out that the end-user seat is tied to an organization rather than an individual?

@vaikas:

I shouldn't have made that distinction around `The end-user seat would be the "tie-breaker"`. I think this was me just capturing some of steerings' thoughts when we discussed live.

**Comment by jberkus** [comment]
FWIW, running both elections in parallel won't be technically hard, at all, given our software.

However, establishing the end-user electorate would potentially be hard.  You'd need some way to measure end-user activity.

**Comment by jberkus** [comment]
In fact:  suggestion.

For the 2021 election, do the above as suggested ... have the SC appoint.

For 2022, what if we had an "end user registry"?  A place where users could fill out a survey and give us their user stories.  This would help with both Knative promotion and development, and would then give us a list of folks who can vote on/run for the end-user seat.
