### ISSUE TITLE
Document process to create new repos in knative orgs

### ISSUE THREAD

**Issue by pmorie** [knative/community#76]
Raised by @coryrc on the Jan 30th TOC meeting, there is currently not a documented process to have new repos considered for creation, and there should be.

**Comment by pmorie** [comment]
Here's the k8s process as a reference: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories

**Comment by evankanderson** [comment]
A few extra points:

* We have two orgs; `knative` and `knative-community` (which has been pointed out is both empty and confusing when compared with `knative/community`). We should either abandon the latter or use it as a staging/incubation ground.
* The process should include some guidance about handling dependencies. Ideally, we would have at most a "bush" or a "bushy forest" of dependencies, rather than a full gnarly DAG.

**Comment by rhuss** [comment]
Can we continue to work on this issue ? Currently I'm trying to get a repository `knative/homebrew-client` created which not much luck:

* Sent mail to knative-admins@googlegroups.com
* Asked in #toc-steering-questions

Before bugging @mattmoor again I think it would be a good occasion to establish a process around this not-so-uncommon use case.

It's not so much about how the repo looks like (this is also important though), but how to _start_ that process.

**Comment by evankanderson** [comment]
#149 and #125 cover much of this now, I think?

**Comment by evankanderson** [comment]
(Leaving in SC backlog to close or pursue further)

**Comment by evankanderson** [comment]
With #125 in, I think we can:

/close
