### ISSUE TITLE
Knative should target "mainstream" versions of k8s

### ISSUE THREAD

**Issue by rgregg** [knative/community#80]
With the recent updates moving Knative to require k8s 1.15, we've made it difficult for many users to adopt Knative in their cloud platform of choice.

While our general principals for a minimum version of k8s are based on k8s supported versions (e.g. N-2 releases), the major cloud players are all lagging behind. With the requirement of 1.15 as the minimum version, we've effectively made it harder to use Knative with Amazon, Google, Azure, and others.

- [Amazon's highest supported version of k8s](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html) is 1.14.0. 
- Google has 1.16 in the Rapid channel, but the regular channel is still 1.14, and the default if not using channels is 1.13.
- Azure's default version is also incompatible, since they default to N-1, and choose 1.14 right now.
- OpenShift Container Platform's latest release is also using 1.14. 

This means the current release of Knative is not compatible with any of the 3 major public cloud provider's default managed k8s versions. Out of the major contributors to the project, only IBM Cloud has a default that works with Knative. 

This seems like the wrong place for a project that is pushing for customer adoption to be. I realize there is functionality in k8s 1.15 that made it easier to support Knative -- but as a general policy, it seems like sticking too close to k8s head is going to cause us considerable adoption challenges.

**Comment by rgregg** [comment]
cc/ @mattmoor, since we've talked about this in the past.

**Comment by mattmoor** [comment]
cc @vaikas @evankanderson @dgerd @pmorie 

Ack, and this is a tough project vs. product delineation.  The basis for the principle here is simple: we support upstream the version range that is supported by K8s upstream at the time of each release.

As with the CRD webhook issue in 1.14, this is not a theoretical problem; our inability to service upstream Kubernetes materially influences our ability to support Knative on older versions of Kubernetes.  Vendors have wiggle room here, but upstream we do not.

> This seems like the wrong place for a project that is pushing for customer adoption to be. I realize there is functionality in k8s 1.15 that made it easier to support Knative -- but as a general policy, it seems like sticking too close to k8s head is going to cause us considerable adoption challenges.

Honestly this sounds like FUD, can you be more specific?  I am taking from this comment that you have customers in hand that won't adopt 0.11, and would adopt 0.12, but can't because of a 1.15 requirement?

**Comment by evankanderson** [comment]
Assigning to Steering Backlog to determine if we want to change the release process due to major cloud provider lagging on K8s upgrades.

**Comment by vaikas** [comment]
I'm closing this in favor of:
https://github.com/knative/community/issues/245

Reopen if necessary.
