### ISSUE TITLE
GitHub Access cleanup

### ISSUE THREAD

**Issue by bsnchan** [knative/community#84]
The Knative GitHub permissions are in dire need of some cleaning and rethinking. @mattmoor has offered to help clean this up :) 

Proposal [here](https://docs.google.com/document/d/1pCLzTfNP5-_Z9taNK0W5hntyKbP4E5DI4-6n16GpyeU/edit#).

**Comment by mattmoor** [comment]
Thanks @bsnchan !

**Comment by mattmoor** [comment]
I've renamed the existing teams we plan to drop with a `Legacy ...` prefix and created all of the new teams and sub-teams.

I'm going to pause until tomorrow to make sure nobody screams before proceeding to the next phase, which is where folks will definitely start losing privileges.

**Comment by mattmoor** [comment]
At this point access (above "read") is granted exclusively through the new teams, and all existing groups have been dropped to "read" access on any repositories they touch.

For now the game plan is whack-a-mole as folks discover they have lost permissions they need.

In the coming week or so (no rush), I will clean up all of the Legacy teams since they should be redundant with Knative Users for granting Org access, and then this will be complete.

**Comment by mattmoor** [comment]
This is now done, we can keep backfilling as stuff comes up, but there isn't a strong need to keep the old teams around any longer IMO.
