### ISSUE TITLE
WG leads should be able to trigger a dot release job

### ISSUE THREAD

**Issue by pierDipi** [knative/community#897]
Today, WG leads can't trigger a dot release job since
they don't have permissions.

Example error from trying to run a dot release job:

![image](https://user-images.githubusercontent.com/33736985/149741641-c7addc24-14dd-4350-8a92-da6c7f6f3b23.png)

In test infra, we documented how to [trigger a release manually](
https://github.com/knative/test-infra/blob/main/guides/manual_release.md)
but only Knative Release Leads or Technical Oversight Committee can 
trigger such jobs.

This approach doesn't scale as we grow, so we need more people.

* Expected benefits. Who gains the benefits? Why will they benefit?

Users and maintainers.

Triggering a dot release job allows unblocking PRs that can't be merged
due to issues in a different version of the released artifacts or for releasing
critical bug fixes quickly so improved productivity for everyone.

* Expected costs. Who bears the costs? How heavy are they?

The main cost is in the implementation of a new fine-grained
permission model.

The cheapest is to add WG leads to the Knative Release Leads
group. The problem is that they will be able to trigger a release
for all repositories, likely WG leads are trusted people and, 
they will use their judgment to collect consensus with other leads,
or alternatively, we can create a well-defined (async) process for this.

* Timeframe for implementation / rollout.

2 - 4 weeks ?

* Are you willing to drive the process, or is this a request for help?

Yes

**Comment by rhuss** [comment]
+1 for allowing WG Leads to make a release right now and we can think about a more fine-grained authorization model to automatically allow WG leads to release when moving the jobs to the CNCF infrastructure. A drawback of adding WG leads to release leads is that for changes in the WG leads assignment a manual step to update the release leads is required (and must not be forgotten). An automatic sync would be preferred (but then one could adapt the automation to evaluate the OWNERS files directly, too)

**Comment by pierDipi** [comment]
(I don't have permissions to add this issue to the @knative/technical-oversight-committee board, I'd appreciate someone adding this to the https://github.com/orgs/knative/projects/9 project)

**Comment by vaikas** [comment]
Done 👍

**Comment by evankanderson** [comment]
@chizhg to link details for the ACL on running the dot-release jobs

In the short term, we can add the WG leads to the team that can kick off prow jobs, since prow jobs should generally be configured to DTRT and not accept input that subverts the job.

**Comment by evankanderson** [comment]
There is also an auto-release every Tuesday, so without a manual trigger releases will come out on Tuesday anyway.

**Comment by rhuss** [comment]
> There is also an auto-release every Tuesday, so without a manual trigger releases will come out on Tuesday anyway.

Right, but I think it's ok to give WG-leads more control, especially when patch releases are most often about bug fixes which should be able to be delivered faster than with a one-week granularity.

**Comment by pierDipi** [comment]
One more note to this issue, when a dot release job hasn't run yet, there isn't a button to trigger the job in the prow UI, so even TOC can't trigger the job anyway (unless I'm missing something).

![image](https://user-images.githubusercontent.com/33736985/151366949-5e6e68cd-d348-47f5-83a1-bdedac1cc68b.png)

Another option might be to run the periodic job every 2 days (like Monday, Wednesday, and Friday), instead of every Tuesday, and we keep our permission model as it is today.

**Comment by rhuss** [comment]
I think there is a trade-off for when to create a patch release when you want to integrate/backport multiple PRs before cutting a patch release. With one week schedule, the danger that the automatic release kicking in before you are reading with emerging everything to the release branch is smaller as when it runs more often. On the other, when done with integrating fixes, one would like to create a PR asap. Having a signal to trigger such builds manually would be perfect, there "Rerun" button is kind of a workaround that covers 90% of the case. The worst case would be, cutting a release branch on Wednesday and the want to get in a fix immediately because of some problems with the release. So one has to wait for 7 days for the first dotrelease job to run.

A quick fix for such not so uncommon case of a quick fix after a release would be to move the dotrelease jobs to e.g. Thursday instead of Tuesday when we are doing our regular releases. In this case, one has 2 days' time for creating a patch release.

**Comment by evankanderson** [comment]
I think we agree with this in principle, and are waiting for the CNCF infrastructure migration move to complete this.

**Comment by dprotaso** [comment]
I was waiting on the CNCF infra migration - but that's done so this is unblocked. Let me make the infra PR
