### ISSUE TITLE
Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? Or stay on your own Slack?

### ISSUE THREAD

**Issue by csantanapr** [knative/community#953]
Decide what are the next steps for Slack usage

Options:
- Stay with current Slack workspace Paid tier (today's state paid by Google)
- Stay with current Slack workspace Free tier
- Move to channel(s) to Kubernetes Slack
- Move to channel(s) to CNCF Slack

**Comment by csantanapr** [comment]
Related to [INCUBATING PROJECT ONBOARDING] Knative https://github.com/cncf/toc/issues/794

**Comment by rhuss** [comment]
See also #941 for another discussion. I think we should merge both issues.

As mentioned over there in Knative slack we have ~ 60 channels, which is quite a bit for any other target slack host (CNCF/Kubernetes). So we might consider also moving to another chat system like Discord. Alternatively, we could also consolidate our Slack usage so that we can live with fewer channels.

**Comment by rhuss** [comment]
Ah, just checked some other Slack installations, some of them have >2k channels, so the number of channels might not be an issue if we agree on a common `knative-` suffix for the channel names. However we should talk with those Slack admins that we arrive with 60+ channels ;-)

**Comment by csantanapr** [comment]
closing this one as duplicate from #941 
/close
